name: uber_cm_pro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  # Pour la communication en temps réel (Firebase est idéal ici)
  firebase_core: ^2.24.2
  firebase_database: ^10.5.7
<<<<<<< Updated upstream
  provider: ^6.1.5+1
  http: ^1.6.0
  smooth_page_indicator: ^2.0.1
  shared_preferences: ^2.5.4
  image_picker: ^1.2.1
  pinput: ^6.0.2
=======
  http: ^1.1.0
>>>>>>> Stashed changes

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/cm_flag.png
    - assets/images/Français.png
    - assets/images/English.png
    - assets/images/driver_owner.png
    - assets/images/driver_need.png
