name: uber_cm
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.10.0  
  
  http: ^1.6.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  pinput: ^6.0.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  osm_nominatim: ^4.0.1
  flutter_polyline_points: ^3.1.0
  shared_preferences: ^2.2.2
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  google_maps_utils: ^2.0.0+1
  flutter_animarker: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/car_top_view.png
